In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("df_ready.csv")
df

,position,wealth,industry,full_name,age,country_of_residence,city_of_residence,source,citizenship,gender,...,gdp_country,g_tertiary_ed_enroll,g_primary_ed_enroll,life_expectancy,tax_revenue,tax_rate,country_pop,country_lat,country_long,continent
0,1,211000,Fashion & Retail,Bernard Arnault & family,74,France,Paris,LVMH,France,M,...,2715518274227,65.6,102.5,82.5,24.2,60.7,67059887,46.227638,2.213749,Europe
1,2,180000,Automotive,Elon Musk,51,United States,Austin,"Tesla, SpaceX",United States,M,...,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,37.090240,-95.712891,North America
2,3,114000,Technology,Jeff Bezos,59,United States,Medina,Amazon,United States,M,...,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,37.090240,-95.712891,North America
3,4,107000,Technology,Larry Ellison,78,United States,Lanai,Oracle,United States,M,...,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,37.090240,-95.712891,North America
4,5,106000,Finance & Investments,Warren Buffett,92,United States,Omaha,Berkshire Hathaway,United States,M,...,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,37.090240,-95.712891,North America
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2586,2540,1000,Healthcare,Yu Rong,51,China,Shanghai,Health clinics,China,M,...,19910000000000,50.6,100.2,77.0,9.4,59.2,1397715000,35.861660,104.195397,Asia
2587,2540,1000,Food & Beverage,"Richard Yuengling, Jr.",80,United States,Pottsville,Beer,United States,M,...,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,37.090240,-95.712891,North America
2588,2540,1000,Manufacturing,Zhang Gongyun,60,China,Gaomi,Tyre manufacturing machinery,China,M,...,19910000000000,50.6,100.2,77.0,9.4,59.2,1397715000,35.861660,104.195397,Asia
2589,2540,1000,Real Estate,Zhang Guiping & family,71,China,Nanjing,Real estate,China,M,...,19910000000000,50.6,100.2,77.0,9.4,59.2,1397715000,35.861660,104.195397,Asia
2590,2540,1000,Diversified,Inigo Zobel,66,Philippines,Makati,Diversified,Philippines,M,...,376795508680,35.5,107.5,71.1,14.0,43.1,108116615,12.879721,121.774017,Asia

## Data cleaning

In [3]:
df.shape

(2591, 30)

In [4]:
df["position"].nunique()

219

In [5]:
to_drop_cols = ["country_lat", "country_long", "position"]
df = df.drop(to_drop_cols, axis = 1) #explain why later

In [6]:
df

,wealth,industry,full_name,age,country_of_residence,city_of_residence,source,citizenship,gender,birth_date,...,cpi_country,cpi_change_country,gdp_country,g_tertiary_ed_enroll,g_primary_ed_enroll,life_expectancy,tax_revenue,tax_rate,country_pop,continent
0,211000,Fashion & Retail,Bernard Arnault & family,74,France,Paris,LVMH,France,M,1949-03-05,...,110.05,1.1,2715518274227,65.6,102.5,82.5,24.2,60.7,67059887,Europe
1,180000,Automotive,Elon Musk,51,United States,Austin,"Tesla, SpaceX",United States,M,1971-06-28,...,117.24,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America
2,114000,Technology,Jeff Bezos,59,United States,Medina,Amazon,United States,M,1964-01-12,...,117.24,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America
3,107000,Technology,Larry Ellison,78,United States,Lanai,Oracle,United States,M,1944-08-17,...,117.24,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America
4,106000,Finance & Investments,Warren Buffett,92,United States,Omaha,Berkshire Hathaway,United States,M,1930-08-30,...,117.24,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2586,1000,Healthcare,Yu Rong,51,China,Shanghai,Health clinics,China,M,1971-12-14,...,125.08,2.9,19910000000000,50.6,100.2,77.0,9.4,59.2,1397715000,Asia
2587,1000,Food & Beverage,"Richard Yuengling, Jr.",80,United States,Pottsville,Beer,United States,M,1943-03-10,...,117.24,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America
2588,1000,Manufacturing,Zhang Gongyun,60,China,Gaomi,Tyre manufacturing machinery,China,M,1962-12-18,...,125.08,2.9,19910000000000,50.6,100.2,77.0,9.4,59.2,1397715000,Asia
2589,1000,Real Estate,Zhang Guiping & family,71,China,Nanjing,Real estate,China,M,1951-08-21,...,125.08,2.9,19910000000000,50.6,100.2,77.0,9.4,59.2,1397715000,Asia
2590,1000,Diversified,Inigo Zobel,66,Philippines,Makati,Diversified,Philippines,M,1956-11-01,...,129.61,2.5,376795508680,35.5,107.5,71.1,14.0,43.1,108116615,Asia

In [7]:
df.info() #it does not have null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2591 entries, 0 to 2590
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   wealth                2591 non-null   int64
 1   industry              2591 non-null   object
 2   full_name             2591 non-null   object
 3   age                   2591 non-null   int64
 4   country_of_residence  2591 non-null   object
 5   city_of_residence     2591 non-null   object
 6   source                2591 non-null   object
 7   citizenship           2591 non-null   object
 8   gender                2591 non-null   object
 9   birth_date            2591 non-null   object
 10  last_name             2591 non-null   object
 11  first_name            2591 non-null   object
 12  residence_state       2591 non-null   object
 13  residence_region      2591 non-null   object
 14  birth_year            2591 non-null   int64
 15  birth_month           2591 non-null   int64
 16  birth_day             2591 non-null   int64
 17  cpi_country           2591 non-null   object
 18  cpi_change_country    2591 non-null   object
 19  gdp_country           2591 non-null   int64
 20  g_tertiary_ed_enroll  2591 non-null   float64
 21  g_primary_ed_enroll   2591 non-null   float64
 22  life_expectancy       2591 non-null   float64
 23  tax_revenue           2591 non-null   float64
 24  tax_rate              2591 non-null   float64
 25  country_pop           2591 non-null   int64
 26  continent             2591 non-null   object
dtypes: float64(5), int64(7), object(15)
memory usage: 546.7+ KB

In [8]:
duplicate_rows = df.duplicated().nunique() #no duplicates
missing_values = df.isnull().sum().sum()

In [9]:
print(f"there are {duplicate_rows} duplicate rows and {missing_values} missing values")

there are 1 duplicate rows and 0 missing values

In [10]:
df["g_primary_ed_enroll"] #consider this later. Ask for Liana's opinion

0       102.5
1       101.8
2       101.8
3       101.8
4       101.8
        ...
2586    100.2
2587    101.8
2588    100.2
2589    100.2
2590    107.5
Name: g_primary_ed_enroll, Length: 2591, dtype: float64

In [11]:
min_primary = np.min(df["g_primary_ed_enroll"])
min_primary
max_primary = np.max(df["g_primary_ed_enroll"])
max_primary

142.1

In [12]:
df["g_primary_ed_enroll"].describe()

count    2591.000000
mean      100.232420
std        11.966391
min         0.000000
25%       100.200000
50%       101.800000
75%       102.600000
max       142.100000
Name: g_primary_ed_enroll, dtype: float64

In [13]:
df.describe()

,wealth,age,birth_year,birth_month,birth_day,gdp_country,g_tertiary_ed_enroll,g_primary_ed_enroll,life_expectancy,tax_revenue,tax_rate,country_pop
count,2591.000000,2591.000000,2591.000000,2591.000000,2591.000000,2.591000e+03,2591.000000,2591.000000,2591.000000,2591.000000,2591.000000,2.591000e+03
mean,4666.190660,65.252798,1957.133925,5.646083,11.882671,1.102966e+13,64.125743,100.232420,78.409101,12.422926,44.548012,4.837733e+08
std,9917.104258,13.055442,13.074254,3.732279,9.941884,9.641891e+12,24.527813,11.966391,3.910509,5.275224,12.212804,5.497567e+08
min,1000.000000,18.000000,1921.000000,1.000000,1.000000,1.044779e+09,0.000000,0.000000,54.300000,0.000000,0.000000,3.112200e+04
25%,1500.000000,56.000000,1948.000000,2.000000,1.000000,1.394116e+12,50.600000,100.200000,77.000000,9.500000,36.600000,6.029740e+07
50%,2400.000000,65.000000,1957.000000,5.000000,10.000000,5.081770e+12,63.400000,101.800000,78.500000,9.600000,46.100000,3.282395e+08
75%,4300.000000,75.000000,1966.000000,9.000000,21.000000,2.142770e+13,88.200000,102.600000,81.300000,12.800000,59.200000,1.366418e+09
max,211000.000000,101.000000,2004.000000,12.000000,31.000000,2.142770e+13,136.600000,142.100000,85.940000,37.200000,106.300000,1.397715e+09

In [39]:
df["wealth(bln)"] = df["wealth"]/1000

,industry,full_name,age,country_of_residence,city_of_residence,source,citizenship,gender,birth_date,last_name,...,cpi_change_country,gdp_country,g_tertiary_ed_enroll,g_primary_ed_enroll,life_expectancy,tax_revenue,tax_rate,country_pop,continent,wealth(bln)
0,Fashion & Retail,Bernard Arnault & family,74,France,Paris,LVMH,France,M,1949-03-05,Arnault,...,1.1,2715518274227,65.6,102.5,82.5,24.2,60.7,67059887,Europe,0.211
1,Automotive,Elon Musk,51,United States,Austin,"Tesla, SpaceX",United States,M,1971-06-28,Musk,...,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America,0.180
2,Technology,Jeff Bezos,59,United States,Medina,Amazon,United States,M,1964-01-12,Bezos,...,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America,0.114
3,Technology,Larry Ellison,78,United States,Lanai,Oracle,United States,M,1944-08-17,Ellison,...,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America,0.107
4,Finance & Investments,Warren Buffett,92,United States,Omaha,Berkshire Hathaway,United States,M,1930-08-30,Buffett,...,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America,0.106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2586,Healthcare,Yu Rong,51,China,Shanghai,Health clinics,China,M,1971-12-14,Yu,...,2.9,19910000000000,50.6,100.2,77.0,9.4,59.2,1397715000,Asia,0.001
2587,Food & Beverage,"Richard Yuengling, Jr.",80,United States,Pottsville,Beer,United States,M,1943-03-10,Yuengling,...,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America,0.001
2588,Manufacturing,Zhang Gongyun,60,China,Gaomi,Tyre manufacturing machinery,China,M,1962-12-18,Zhang,...,2.9,19910000000000,50.6,100.2,77.0,9.4,59.2,1397715000,Asia,0.001
2589,Real Estate,Zhang Guiping & family,71,China,Nanjing,Real estate,China,M,1951-08-21,Zhang,...,2.9,19910000000000,50.6,100.2,77.0,9.4,59.2,1397715000,Asia,0.001
2590,Diversified,Inigo Zobel,66,Philippines,Makati,Diversified,Philippines,M,1956-11-01,Zobel,...,2.5,376795508680,35.5,107.5,71.1,14.0,43.1,108116615,Asia,0.001

In [14]:
df.drop("wealth", axis = 1, inplace = True)
df

,industry,full_name,age,country_of_residence,city_of_residence,source,citizenship,gender,birth_date,last_name,...,cpi_country,cpi_change_country,gdp_country,g_tertiary_ed_enroll,g_primary_ed_enroll,life_expectancy,tax_revenue,tax_rate,country_pop,continent
0,Fashion & Retail,Bernard Arnault & family,74,France,Paris,LVMH,France,M,1949-03-05,Arnault,...,110.05,1.1,2715518274227,65.6,102.5,82.5,24.2,60.7,67059887,Europe
1,Automotive,Elon Musk,51,United States,Austin,"Tesla, SpaceX",United States,M,1971-06-28,Musk,...,117.24,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America
2,Technology,Jeff Bezos,59,United States,Medina,Amazon,United States,M,1964-01-12,Bezos,...,117.24,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America
3,Technology,Larry Ellison,78,United States,Lanai,Oracle,United States,M,1944-08-17,Ellison,...,117.24,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America
4,Finance & Investments,Warren Buffett,92,United States,Omaha,Berkshire Hathaway,United States,M,1930-08-30,Buffett,...,117.24,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2586,Healthcare,Yu Rong,51,China,Shanghai,Health clinics,China,M,1971-12-14,Yu,...,125.08,2.9,19910000000000,50.6,100.2,77.0,9.4,59.2,1397715000,Asia
2587,Food & Beverage,"Richard Yuengling, Jr.",80,United States,Pottsville,Beer,United States,M,1943-03-10,Yuengling,...,117.24,7.5,21427700000000,88.2,101.8,78.5,9.6,36.6,328239523,North America
2588,Manufacturing,Zhang Gongyun,60,China,Gaomi,Tyre manufacturing machinery,China,M,1962-12-18,Zhang,...,125.08,2.9,19910000000000,50.6,100.2,77.0,9.4,59.2,1397715000,Asia
2589,Real Estate,Zhang Guiping & family,71,China,Nanjing,Real estate,China,M,1951-08-21,Zhang,...,125.08,2.9,19910000000000,50.6,100.2,77.0,9.4,59.2,1397715000,Asia
2590,Diversified,Inigo Zobel,66,Philippines,Makati,Diversified,Philippines,M,1956-11-01,Zobel,...,129.61,2.5,376795508680,35.5,107.5,71.1,14.0,43.1,108116615,Asia

ValueError: operands could not be broadcast together with shapes (11,) (26,)

### Ideas for plotting

1.) Scatter plot connecting the age(calculated in a way that it's continuos) and wealth

2.) Scatter plot relating the wealth/revenue with the tax rate

3.) Here CPI can have two meanings Corruption Perceptions Index or Consumer price indexes. I think it is the latter, can be correlated with the wealth again or with the tax rate.

4.) Wealth, tax rates, gdp by continents/countries. Plotted as a bar plot

5.) Find whether anyone is armenian

6.) the frequencies of the birthdays/birth months

7.) male/female comparison in a bar plot

8.) age distribution

9.)

In [4]:
df.shape

(2591, 30)